# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b4684ea23b119f7cde0e3a1d6b654f36"
application_url = "https://log-associated-ellis-calculate.trycloudflare.com"
embedded = true
name = "teifi-beso-app"
handle = "teifi-beso-app"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_inventory, write_inventory"

[auth]
redirect_urls = [
  "https://log-associated-ellis-calculate.trycloudflare.com/auth/callback",
  "https://log-associated-ellis-calculate.trycloudflare.com/auth/shopify/callback",
  "https://log-associated-ellis-calculate.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "beso-demo-store.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
