# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b557b91e9cd94f4cc1b8eba5771e3663"
application_url = "https://fax-measurement-resorts-declared.trycloudflare.com"
embedded = true
name = "teifi-beso-app"
handle = "teifi-beso-app-1"

[build]
include_config_on_deploy = true
dev_store_url = "beso-demo-store.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory, write_products"

[auth]
redirect_urls = [
  "https://fax-measurement-resorts-declared.trycloudflare.com/auth/callback",
  "https://fax-measurement-resorts-declared.trycloudflare.com/auth/shopify/callback",
  "https://fax-measurement-resorts-declared.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
